# Derived from GitHub's c-cpp.yml file
name: Autoconf CI

on: [push, pull_request]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run: git submodule update --init
    - name: configure
      run: ./bootstrap; ./configure; # CC="gcc -fsanitize=address"
    - name: make
      run: make
    - name: make check
      run: make check
    #- name: make distcheck
    #  run: make distcheck

  osx-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Homebrew packages
      run: brew update --preinstall; brew install autoconf automake libtool
    - name: submodule
      run: git submodule update --init
    - name: configure
      run: ./bootstrap; ./configure
    - name: make
      run: make
    - name: make check
      run: make check
